// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl7S_QJKaFn_gwU1XYu9pIjOY1o0Tl0Sk',
    appId: '1:11786937272:android:2294ef2c68e4a8f654e54d',
    messagingSenderId: '11786937272',
    projectId: 'kelimbo-c1253',
    storageBucket: 'kelimbo-c1253.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUw78CT2e9G3HoU0zs36sbZNr-XSHkNrY',
    appId: '1:11786937272:ios:9d241b5e3bbdd65d54e54d',
    messagingSenderId: '11786937272',
    projectId: 'kelimbo-c1253',
    storageBucket: 'kelimbo-c1253.appspot.com',
    androidClientId: '11786937272-bd23gmm78rch7a7ufr62j67gguaecurc.apps.googleusercontent.com',
    iosClientId: '11786937272-jld8utpvc4kdbsejl2uaq4rhc6660f8n.apps.googleusercontent.com',
    iosBundleId: 'com.example.kelimboAdmin',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5jy4sfMUPNQA5FEVFRi-ZTk5_yRhmR1c',
    appId: '1:11786937272:web:1f5de1682a4c2f3a54e54d',
    messagingSenderId: '11786937272',
    projectId: 'kelimbo-c1253',
    authDomain: 'kelimbo-c1253.firebaseapp.com',
    storageBucket: 'kelimbo-c1253.appspot.com',
    measurementId: 'G-CW6YJ3CZZ4',
  );

}